### ISSUE TITLE
Unexpected token trying to include an svg

### ISSUE THREAD

**Issue by antony** [rollup/rollup-plugin-url#7] opened 2017-05-13 10:48 UTC
Trying to include some svg files sadly does not work at all, it appears to be trying to include the raw XML

```
{ Error: Unexpected token
    at error (/home/ant/Projects/vudash-demo/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/home/ant/Projects/vudash-demo/node_modules/rollup/dist/rollup.js:8007:2)
    at tryParse (/home/ant/Projects/vudash-demo/node_modules/rollup/dist/rollup.js:7710:10)
    at new Module (/home/ant/Projects/vudash-demo/node_modules/rollup/dist/rollup.js:7745:14)
    at /home/ant/Projects/vudash-demo/node_modules/rollup/dist/rollup.js:9495:17
  code: 'PARSE_ERROR',
  pos: 0,
  loc: 
   { file: '/home/ant/Projects/vudash/packages/widget-ci/src/client/images/passed.svg',
     line: 1,
     column: 0 },
  frame: '1: <?xml version="1.0" encoding="utf-8"?>\r\n   ^\n2: <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\r\n3: <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1000 1000" xml:space="preserve">\r' }

```

**Comment by Ashot-KR** [comment] 2017-05-13 11:27
Hi, it's strange. Can you provide your rollup config?

**Comment by antony** [comment] 2017-05-13 11:45
```
'use strict'

const svelte = require('rollup-plugin-svelte')
const resolve = require('rollup-plugin-node-resolve')
const commonjs = require('rollup-plugin-commonjs')
const memory = require('rollup-plugin-memory')
const css = require('rollup-plugin-postcss')
const url = require('rollup-plugin-url')

exports.build = function (source) {
  return {
    entry: {
      path: 'dashboard.js',
      contents: source
    },
    dest: 'bundle.js',
    format: 'iife',
    plugins: [
      memory(),
      commonjs(),
      resolve({
        customResolveOptions: {
          moduleDirectory: 'node_modules'
        }
      }),
      url(),
      css(),
      svelte()
    ]
  }
}
```

**Comment by Ashot-KR** [comment] 2017-05-13 20:48
@antony i can't reproduce issue, can you create a repo with full example, please?

**Comment by antony** [comment] 2017-05-14 13:12
Hi,

Sure thing - will do!

**Comment by Ashot-KR** [comment] 2018-10-04 12:21
Can't reproduce, so close this one

**Closed as completed by Ashot-KR** 2018-10-04 12:21 UTC
